name: Deploy Go Lambda Function

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  generate-lambda-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Lambda ZIP
        run: |
          # Build your Go Lambda code
          go build -o main
          zip -j lambda.zip main
          echo "Lambda ZIP generated successfully"
        working-directory: ${{ github.workspace }}

      - name: Upload Lambda ZIP Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda-artifact
          path: ./lambda.zip



  deploy:
    runs-on: ubuntu-latest

    needs: generate-lambda-zip

    outputs:
      lambda_bucket_name: ${{ steps.read-output.outputs.lambda_bucket_name }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set aws_default_region $AWS_DEFAULT_REGION

    steps:
      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::726032046446:role/github-actions-role
          role-session-name: samplerolesession
          aws-region: ${{env.AWS_DEFAULT_REGION}}
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x

      - name: Download Lambda ZIP Artifact
        uses: actions/download-artifact@v2
        with:
          name: lambda-artifact
          path: ./lambda.zip

      - name: Terraform Apply Stage 1
        run: |
          export LANG="en_US.UTF-8"
          cd ./terraform/stage_1
          terraform init
          terraform apply -auto-approve
          terraform output bucket_name | sed 's/^ *"\(.*\)" *$/\1/' > output.txt
          json_data=$(cat output.txt)
          echo "JSON_DATA: \"$json_data\""
          LAMBDA_BUCKET_NAME="$(echo $json_data | grep -o 'bucket_name[[:space:]]*[^[:space:]]*' | awk '{print $2}')"
          echo "LAMBDA_BUCKET_NAME: ${LAMBDA_BUCKET_NAME}"
          echo "LAMBDA_BUCKET_NAME=${LAMBDA_BUCKET_NAME}" >> $GITHUB_ENV

      - name: Upload Lambda Code to S3
        run: |
          aws s3 cp lambda.zip/lambda.zip s3://${{ env.LAMBDA_BUCKET_NAME }}/lambda.zip
        if: success()

      - name: Terraform Apply Stage 2
        run: |
          cd ./terraform/stage_2
          terraform init
          terraform apply -auto-approve

      - name: Deploy Lambda Code
        run: |
          aws lambda update-function-code --function-name ${{ needs.deploy.outputs.lambda_function_name }} --s3-bucket ${{ needs.deploy.outputs.lambda_bucket_name }} --s3-key lambda.zip
        if: success()

      - name: Clean Up
        run: terraform destroy -auto-approve ./terraform
        if: always()
