name: Deploy Go Lambda Function

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  generate-lambda-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Lambda ZIP
        run: |
          # Build your Go Lambda code
          go build -o main ./lambda
          zip -j lambda.zip main
          echo "Lambda ZIP generated successfully"
        working-directory: ${{ github.workspace }}
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::726032046446:role/github-actions-role
          role-session-name: samplerolesession
          aws-region: ${{env.AWS_DEFAULT_REGION}}
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x

      - name: Upload Lambda Code to S3
        run: |
          aws s3 cp lambda.zip s3://${{ needs.deploy.outputs.lambda_bucket_name }}/lambda.zip
        if: success()

      - name: Deploy Lambda Code
        run: |
          aws lambda update-function-code --function-name ${{ needs.deploy.outputs.lambda_function_name }} --s3-bucket ${{ needs.deploy.outputs.lambda_bucket_name }} --s3-key lambda.zip
        if: success()

      - name: Clean Up
        run: terraform destroy -auto-approve ./terraform
        if: always()

      - name: Upload Lambda Code to S3
        run: |
          # Build your Go Lambda code
          go build -o main ./lambda
          zip -j lambda.zip main
          aws s3 cp lambda.zip s3://${{ needs.deploy.outputs.lambda_bucket_name }}/lambda.zip

      - name: Deploy Lambda Code
        run: |
          aws lambda update-function-code --function-name ${{ needs.deploy.outputs.lambda_function_name }} --s3-bucket ${{ needs.deploy.outputs.lambda_bucket_name }} --s3-key lambda.zip

      
