name: Deploy Resum-API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      LAMBDA_FUNCTION_NAME: ${{ steps.outputs.lambda_function_name }}
      LAMBDA_BUCKET_NAME: ${{ steps.outputs.lambda_bucket_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x

      - name: Initialize Terraform
        run: terraform init ./terraform

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve ./terraform

      - name: Upload Lambda Code to S3
        run: |
          # Build Go Lambda code
          go build -o main ./lambda
          zip -j lambda.zip main
          aws s3 cp lambda.zip s3://${{ env.LAMBDA_BUCKET_NAME }}/lambda.zip

      - name: Deploy Lambda Code
        run: |
          aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --s3-bucket ${{ env.LAMBDA_BUCKET_NAME }} --s3-key lambda.zip

      - name: Clean Up
        run: terraform destroy -auto-approve ./terraform
        if: always()